spring:
  kafka:
    properties:
      schema.registry.url: http://localhost:8081

assembly-ai:
  webhook-url: https://b55e-2a02-a317-e347-7000-d191-67f8-ec9-a7e4.eu.ngrok.io/music-bot-service/assembly-ai